In [16]:
%matplotlib tk
import matplotlib.pyplot as plt
import numpy as np
import pickle

from cameraRobotCalibration import *

import time


from wandelpy.azurekinect2 import AzureKinect, Camera 
try:
    kinect = AzureKinect() 
    print("\n\nSuccess with connecting to camera.")
except:
    time.sleep(1)
    print("Camera couldn't be connected. Use the notebook with loading captures.")
    
    
    
# To autoreload imported libraries:    
%load_ext autoreload
%autoreload 2

[2022-05-09 08:20:13.597] [error] [t=67704] /home/patrick/development/3rdparty/Azure-Kinect-Sensor-SDK/src/usbcommand/usbcommand.c (748): usb_cmd_io(). Error calling libusb_bulk_transfer for initial tx, result:LIBUSB_ERROR_NO_DEVICE
[2022-05-09 08:20:13.597] [error] [t=67704] /home/patrick/development/3rdparty/Azure-Kinect-Sensor-SDK/src/usbcommand/usbcommand.c (950): usb_cmd_io(usbcmd_handle, cmd, p_cmd_data, cmd_data_size, NULL, 0, p_data, data_size, NULL, cmd_status) returned failure in usb_cmd_write_with_status()
[2022-05-09 08:20:13.597] [error] [t=67704] /home/patrick/development/3rdparty/Azure-Kinect-Sensor-SDK/src/depth_mcu/depth_mcu.c (355): usb_cmd_write_with_status(depthmcu->usb_cmd, DEV_CMD_DEPTH_STREAM_STOP, NULL, 0, NULL, 0, &cmd_status) returned failure in depthmcu_depth_stop_streaming()
[2022-05-09 08:20:13.597] [error] [t=67704] /home/patrick/development/3rdparty/Azure-Kinect-Sensor-SDK/src/usbcommand/usbcommand.c (748): usb_cmd_io(). Error calling libusb_bulk_transfer

In [7]:
# Either load a capture
# Load the captures:
fileLoad = 'test2.pkl'   # 2 completely different images
fileLoad = 'set2.pkl'    # Images with one object difference - direciton into a corner
fileLoad = 'cell1.pkl'    # Image in the cell - Bumpy metal piece
fileLoad = 'cell2.pkl'    # Image in the cell - Thick wooden piece
fileLoad = 'cell3.pkl'    # Image in the cell - Thin wooden plank
fileLoad = 'cell4.pkl'    # Image in the cell - Thin wooden plank - at an angle

# V2: means the sCapture was updated - to have color_depth2d and depth3d
fileLoad = 'V2_cardboard_01.pkl'    # Cardboard box with a stick-it note 
fileLoad = 'V2_cardboard_02.pkl'    # L-shaped box with 3 stick-it notes 
fileLoad = 'V2_cardboard_03.pkl'    # Camera angled - Zigzag shaped box with 3 stick-it notes 


fileLoad = 'V2_cardboard_03.pkl'


# fileLoad = 'set1.pkl'    # Images with one object difference
with open(fileLoad, 'rb') as fileIn:
    sCapture1, sCapture2 = pickle.load(fileIn)

print(f'File {fileLoad} loaded.')

sCapture_Calibration = sCapture2

File V2_cardboard_03.pkl loaded.


In [17]:
# Or capture an image:
#TODO: test it
capture = kinect() 
sCapture_Calibration = simplifiedCapture(capture)

In [18]:
# Calibration - click points on the camera image    
points3D, points = get_clicked3DPointsFromCapture(sCapture_Calibration, max_IR=1500)

print("pixel coordinates of clicked points:")
print(points)
print("3D coordinates of clicked points:")
print(points3D)

print('_______________________________ Copy between lines __________________________________')
print('int16 = np.int16\n')
print('# Calibration points in image - for preview')
print('calibrationPointsImg_CS =', points.__repr__(), '\n')

print("# Calibration points in Camera system (in order: O, X, Y)")
print(f'calibrationPoints3D_CS = np.{points3D.__repr__()}')

print('_____________________________________________________________________________________')

INFO - 2022-05-09 08:20:39,710 - blocking_input - Event 1
INFO - 2022-05-09 08:20:39,711 - blocking_input - input 1: 244.925211, 267.631310
INFO - 2022-05-09 08:20:42,837 - blocking_input - Event 1
INFO - 2022-05-09 08:20:42,837 - blocking_input - input 1: 370.880570, 263.791208
INFO - 2022-05-09 08:20:47,280 - blocking_input - Event 1
INFO - 2022-05-09 08:20:47,280 - blocking_input - input 1: 245.693232, 167.788648


pixel coordinates of clicked points:
[[268, 245], [264, 371], [168, 246]]
3D coordinates of clicked points:
[[-153 -141 1037]
 [ 110 -150 1044]
 [-152 -351 1008]]
_______________________________ Copy between lines __________________________________
int16 = np.int16

# Calibration points in image - for preview
calibrationPointsImg_CS = [[268, 245], [264, 371], [168, 246]] 

# Calibration points in Camera system (in order: O, X, Y)
calibrationPoints3D_CS = np.array([[-153, -141, 1037],
       [ 110, -150, 1044],
       [-152, -351, 1008]], dtype=int16)
_____________________________________________________________________________________


Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/home/erik/.virtualenvs/veSeamFinder/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 476, in delayed_destroy
    self.window.destroy()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2311, in destroy
    for c in list(self.children.values()): c.destroy()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2583, in destroy
    Misc.destroy(self)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 640, in destroy
    self.tk.deletecommand(name)
_tkinter.TclError: can't delete Tcl command


In [25]:
int16 = np.int16

# Calibration points in image - for preview
calibrationPointsImg_CS = [[268, 245], [264, 371], [168, 246]] 

# Calibration points in Camera system (in order: O, X, Y)
calibrationPoints3D_CS = np.array([[-153, -141, 1037],
       [ 110, -150, 1044],
       [-152, -351, 998]], dtype=int16)
# _______________ paste above line ____________________________________________

# Calibration points in Robot system (in order: O, X, Y)
# ENTER MANUALLY (read from robot pendant)
calibrationPoints3D_RS = np.array([
        [-519.2, -340.3, -27.8],
        [-520.5, -604.2, -27.2],
        [0, 100,  0]], dtype=int16)

# calibrationPoints3D_RS = np.array([
#         [0, 0,  0],
#         [100, 0,  0],
#         [0, 100,  0]], dtype=int16)

In [26]:
calib_cameraRobot = CalibrationCameraRobot(calibrationPoints3D_RS, 
                               calibrationPoints3D_CS, calibrationPointsImg_CS, 
                               sCapture_Calibration)  
    
H = calib_cameraRobot.get_transformation_CR()
calib_cameraRobot.print_repr_transformation_CR()

# Transformation H_CR:
H_CR = np.array([[-3.41722790e-02, -9.90631633e-01, -1.32216576e-01,
        -5.26798830e+02],
       [-9.98939322e-01,  3.79410574e-02, -2.60903634e-02,
        -4.60432320e+02],
       [ 3.08623760e-02,  1.31184769e-01, -9.90877424e-01,
         1.02375889e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])


libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action bind
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action change
libusb: error [udev_hotplug_event] ignoring udev action bind


In [11]:
# Transformation H_CR:
H_CR = np.array([[-3.55709795e-02, -9.95649794e-01, -8.61173193e-02,
        -5.75525321e+02],
       [-9.98934024e-01,  3.79600656e-02, -2.62649818e-02,
        -4.60247750e+02],
       [ 2.94197428e-02,  8.50912492e-02, -9.95938732e-01,
         1.02228755e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

# Transformation H_CR - for image 'V2_cardboard_03.pkl :
H_CR = np.array([[ 9.16305722e-01,  2.98453864e-01,  2.67037667e-01,
        -5.98740339e+01],
       [ 3.13802101e-01, -9.49358194e-01, -1.57245199e-02,
        -1.12928275e+02],
       [ 2.48821354e-01,  9.82054485e-02, -9.63557795e-01,
         8.00976470e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
print(H_CR)

[[ 9.16305722e-01  2.98453864e-01  2.67037667e-01 -5.98740339e+01]
 [ 3.13802101e-01 -9.49358194e-01 -1.57245199e-02 -1.12928275e+02]
 [ 2.48821354e-01  9.82054485e-02 -9.63557795e-01  8.00976470e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
